language: node_js

node_js:
- 14

env:
  global: 
    - secure: dJBIJY6emNNVaHi/tW103LKhmhpUsYuoWr+QGUk70Q6dQ1Ps25rpbSgg42m3/Rh0TApekwuQ0tJRXtxlcIydPpzS2/rUR29mihE3Y5BKUy+vA/0DwkW1SPP9OU0eFhPYaWhmGmJeoTbjnn1qTsHhb1OOQEFfmewqmPai5hvXAbAAp+NCbtTlFY+6pC9UChNwcvffoi7bEP9fQJs5bQZ4n9Vcb1X4E7Y8nd+srzVAB7KIVy/ESENlH6C1ObQD71wuN0psNF/AUI++lPgaCCmlxVqd11yqSUakT79ItSvT+8nvIJpdHwxqgA4Z7h46gl50/L2Cw1JUNJto+oOjafQkniudCX6L/xGO5LtslT5cO3rYkkC73Pv0DlIFQyYXnHlVxoT7YoAggu/xSiIVyw0oIQd+2itKPIFMDX+ZeweOGDdszppatpxw0tegVNLv9T+Hgt0T6/BSMrGqwGvuipCyDe8NcVBmwTGohkFjR7PszkV7BtYLSbc4qrafAsIU01GBeXM0PIvgkAb8MhaM5pSy1tvlZ12LR3iPOMrDIa2GfFT8MAf3bK3CzhV3sOXy6vunxOHKz00R8nvqhjDE16SRbkpfi+SeuYOlau06ToxK1Y61Pn7JWOlwURCX/Zr7U99S3cPbqaeuThK8cDrRrEU0zC8FYXyS30JXSXrUd0Um4oI=

script: make publish
